# NumPy

In [1]:
import numpy as np

In [2]:
range = np.arange(15)
print(range)
print(type(range))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


multiple ways of defining:

In [11]:
a1 = np.array([1, 2, 3])
print(a1)

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print(a2.shape)

a3 = np.array([[1, [2, 6], 3], [4, 5, 6]])
print(a3)
print(a3.shape)

a4 = np.array([[[1, 10], [2, 6], [3, 8]], [[4, 5], [6, 76], [3, 45]]])
print(a4)
print(a4.shape)

print("create a range with limits and increment:")
print(np.arange(1, 20, 0.5))

print("or create specifying limits and number of objects, usefull to control length")
linsp = np.linspace(0, 1, 16)
print(linsp)
print("we can now reshape to create a new object")
print(linsp.reshape(4, 4))
print(linsp)
print("or we can change in place using resize")
linsp.resize((2, 2, 2, 2))
print(linsp)

print("If we specify fewer dimensions when indexing, it will be assumed first are given and the rest is full")
print(linsp[1])
print("three dots say a number of full dimensions")
print(linsp[0, :, :, 1])
print(linsp[0, ..., 1])

print("The view above is confusing when printed, let's make it look more familiar by expanding dimensions")
view = linsp[0, ..., 1]
print(view[np.newaxis, :, np.newaxis])

[1 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 list([2, 6]) 3]
 [4 5 6]]
(2, 3)
[[[ 1 10]
  [ 2  6]
  [ 3  8]]

 [[ 4  5]
  [ 6 76]
  [ 3 45]]]
(2, 3, 2)
create a range with limits and increment:
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]
or create specifying limits and number of objects, usefull to control length
[0.         0.06666667 0.13333333 0.2        0.26666667 0.33333333
 0.4        0.46666667 0.53333333 0.6        0.66666667 0.73333333
 0.8        0.86666667 0.93333333 1.        ]
we can now reshape to create a new object
[[0.         0.06666667 0.13333333 0.2       ]
 [0.26666667 0.33333333 0.4        0.46666667]
 [0.53333333 0.6        0.66666667 0.73333333]
 [0.8        0.86666667 0.93333333 1.        ]]
[0.         0.06666667 0.13333333 0.2        0.26666667 0.33333333
 0.4        0.46666667 0.53333333 0.6        0.66666667 0.733333

### Prinitng arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

* the last axis is printed from left to right,
* the second-to-last is printed from top to bottom,
* the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

> One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [4]:
from numpy import newaxis

print(a1)
print("Use newaxis to view a1 not as row but as column")
print(a1[:, newaxis])
print("we can do the same with 3 dimensions")
print(a1[:, newaxis, newaxis])
print(a1[newaxis, :, newaxis])

print("All standard operations are performed element wise")
print(a2 ** 3)
print("matrix multiplication with @")
a5 = np.linspace(0, 50, 15).reshape(3,5)
print(a5)
print(a2@a5)

[1 2 3]
Use newaxis to view a1 not as row but as column
[[1]
 [2]
 [3]]
we can do the same with 3 dimensions
[[[1]]

 [[2]]

 [[3]]]
[[[1]
  [2]
  [3]]]
All standard operations are performed element wise
[[  1   8  27]
 [ 64 125 216]]
matrix multiplication with @
[[ 0.          3.57142857  7.14285714 10.71428571 14.28571429]
 [17.85714286 21.42857143 25.         28.57142857 32.14285714]
 [35.71428571 39.28571429 42.85714286 46.42857143 50.        ]]
[[142.85714286 164.28571429 185.71428571 207.14285714 228.57142857]
 [303.57142857 357.14285714 410.71428571 464.28571429 517.85714286]]


### broadcasting

Broadcasting makes it possible to oparate on arrays without matching sizes.

Shapes are checked from the right -> they have to be either equal or 1

In [18]:
rng1 = np.arange(0, 20)
print(rng1)
rng2 = np.arange(20, 30)
print(rng2)

try:
    rng1 + rng2
except ValueError:
    print(repr(rng1.shape) + " " + repr(rng2.shape))
    
rng1 = rng1[:, newaxis]

print(rng1 + rng2[-5:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
(20,) (10,)
[[25 26 27 28 29]
 [26 27 28 29 30]
 [27 28 29 30 31]
 [28 29 30 31 32]
 [29 30 31 32 33]
 [30 31 32 33 34]
 [31 32 33 34 35]
 [32 33 34 35 36]
 [33 34 35 36 37]
 [34 35 36 37 38]
 [35 36 37 38 39]
 [36 37 38 39 40]
 [37 38 39 40 41]
 [38 39 40 41 42]
 [39 40 41 42 43]
 [40 41 42 43 44]
 [41 42 43 44 45]
 [42 43 44 45 46]
 [43 44 45 46 47]
 [44 45 46 47 48]]
